{{- if .Values.sealedSecrets }}
{{- range $sealedKey, $sealedValue := .Values.sealedSecrets }}
---
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: {{ $sealedValue.name }}
{{- if $sealedValue.annotations }}
  annotations:
{{- range $sealedValue.annotations }}
    {{- . | toYaml | nindent 4 }}
{{- end }}
{{- end }}
spec:
  template:
    type: {{ $sealedValue.type }}
    metadata:
      name: {{ .name }}
{{- if $sealedValue.annotations }}
      annotations:
{{- range $sealedValue.annotations }}
        {{- . | toYaml | nindent 8 }}
{{- end }}
{{- end }}
  encryptedData:
    {{- range $key, $value := $sealedValue.values }}
    {{ $key }}: {{ $value }}
{{- end }}
{{- end }}
{{- end }}